### ISSUE TITLE
[ToC] mobile, scrolling page causes the ToC dropdown to vibrate

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#2545] opened 2020-05-27 16:23 UTC
I'm not sure if this is a bug or an unavoidable behavior - **it seems the ToC dropdown is vibrating up and down when the page is scrolling**, revealing a bit of the page below on above the dropdown.

### To replicate this bug: 

1. go to https://ibmdotcom-react-canary.mybluemix.net/iframe.html?id=patterns-sub-patterns-table-of-contents--with-heading-content
2. narrow window to see mobile ToC (in dropdown form) 
3. open dropdown to select the last item, watch the scrolling vibration
4. repeat by opening the dropdown and select the first item. 

![May-27-2020 12-18-19](https://user-images.githubusercontent.com/15144993/83046068-7458fb00-a014-11ea-824f-a193ccaf6d2e.gif)

**Comment by RaphaelAmadeu** [comment] 2020-06-30 18:44
@shixiedesign 
I'm trying to reproduce this issue,
can you share which browser you got this bug on?

Thanks!

**Comment by RaphaelAmadeu** [comment] 2020-07-24 18:32
I've tried on the lastest version of Chrome, and this issue is not happening, probably it's not a bug on our side.

**Comment by RobertaJHahn** [comment] 2020-07-29 15:44
@shixiedesign We will close this bug if we don't hear from you by Aug 7.

**Closed** 2020-12-16 15:47 UTC
Labels: Airtable Done, bug, dev, package: react, severity 4
