### ISSUE TITLE
Global Masthead Performance Issues: Potentially Degrading User Experience

### ISSUE THREAD

**Issue by KeyboardCowboy** [carbon-design-system/carbon-for-ibm-dotcom#9582] opened 2022-10-20 15:20 UTC
### Description

The Web Components Masthead loads many scripts and there is concern that it is causing a degraded user experience.  We'd like to explore ways to improve load times and/or component weight.

This was brought to light when mobile pages started crashing on iOS and iPadOS the week of October 16.  It turns out there was a significant memory leak in another script that was determined to be the cause, but the masthead was the most recent significant addition to it took the blame.  Still, it brought to light the size of the masthead so we'd like to investigate any performance improvements we could make to help keep the pages as performant as possible.

### Component(s) impacted

Global masthead.

### Browser

Safari

### Carbon for IBM.com version

latest

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

na

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by juanleon9** [comment] 2022-10-21 16:38
We have new information on this issue, the navigation code creates 2/3 of the total number of nodes on IBM pages, which is about 22,000 nodes on both DOM and shadow DOM.

Lighthouse flags pages with DOM trees that:
- Warns when the body element has more than ~800 nodes.
- Errors when the body element has more than ~1,400 nodes.

Attached is a snapshot Lighthouse for https://ww.ibm.com/us-en, which shows 5,255 in the normal DOM, not accounting for the shadow DOM which is over three times larger
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/21178525/197245935-98ed834d-7e79-4b52-a6ba-bc80ac06569f.png">

My recommendation is to backout the new navigation system because of the impact to SEO and paid search and also to overall page performance

**Comment by KeyboardCowboy** [comment] 2022-10-21 17:55
How many nodes did the previous navigation implement?  Are we net + or - with the new navigation?  Also, can we quantify the impact on page performance with some sort of AB test?  The initial issue wasn't load times, but memory usage where the scrips the continued running after the page loaded ate up over 7GB of system memory.

**Comment by andy-blum** [comment] 2022-10-21 18:20
We're definitely adding nodes with the new navigation. There's a considerable amount more complexity

**Comment by jeffchew** [comment] 2022-10-21 18:35
By design, and also showing in number of nodes, the v2 Masthead is more than twice the size of the v1 Masthead.

**Comment by proeung** [comment] 2023-02-08 20:58
Closing out this issue since it has been resolved by https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9595 and https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9602. Feel free to re-open if there are more unresolved issues.

**Closed by proeung** 2023-02-08 20:58 UTC
Labels: bug, dev, package: web components
