### ISSUE TITLE
[Cloud-Masthead]: Implement the lazy load approach for the mega-menu on Cloud pages

### ISSUE THREAD

**Issue by AndaPatrascu** [carbon-design-system/carbon-for-ibm-dotcom#10056] opened 2023-02-16 17:16 UTC
**Engineering info:**  
- Innovation Team engineer: @m4olivei 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2964
- DPO consulting engineer: @IgnacioBecerra 

-----

### Description

This is impacting many Cloud pages. So, it is recommended to implement the lazy load approach for the mega-menu on all IBM pages to enable the services provided by Decibel Insight, now, known as Medallia Digital Experience Analytics (DXA). This has been documented here https://w3.ibm.com/w3publisher/digital-behavior-data-management/blog/661ab090-9244-11ed-ae79-25d164e27ac2 and has been previously reported in GiftHub.
Anything done in the megamenu is independent of the pages and should not affect publishing. From my understanding this is needed at just one Cloud page to flow on all others.

### Component(s) impacted

All ibm.com/cloud pages

### Browser

Microsoft Edge

### Carbon for IBM.com version

-

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

-

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

-

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by jeffchew** [comment] 2023-02-16 18:26
Referencing the previous work here:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9582

**Comment by jeffchew** [comment] 2023-02-16 18:28
FYI @proeung @andy-blum @IgnacioBecerra

**Comment by proeung** [comment] 2023-02-16 18:48
@jeffchew Thanks for pinging us on this issue. Looks like we can utilize the work done in Masthead v2 PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9602) for the Cloud Masthead `<dds-cloud-masthead-container>` that's still being adopted on `/cloud` web segment. Our goal is to eventually, switch the usage of `<dds-cloud-masthead-container>` to using v2 updates `<dds-masthead-container>` on Cloud pages, however, that's not happening anytime soon.

We'll take a look at this issue in our next sprint planning.

@AndaPatrascu What team do you belong to? I'd like to get some information about the stakeholders involved in this issue so that we can provide updates on the status of the fix accordingly.

**Comment by AndaPatrascu** [comment] 2023-02-17 09:50
@proeung I'm part of the Digital Strategy team for Cloud and we are the stakeholders, I took ownership on this particular task. Thank you for making this work, as I see above this can be fixed. Please share the updates on the status of the fix here and I will share them with the team. Also, let me know if you need more complex information from us, that is needed for the fix.

**Comment by AndaPatrascu** [comment] 2023-02-21 06:43
Hello, are there any updates on the current status for Cloud Masthead? Thank you.

**Comment by proeung** [comment] 2023-02-21 17:10
@AndaPatrascu An engineer is assigned to this ticket and we're anticipating these fixes will go into the next release of C4IBM v1.45.0 (Mar 28, 2023: Full Release - see https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9698) as v1.44.0 has already been cut. However, if the timeline is long and this work is considered a high priority, then we can look into getting a patch to the current release cut (v1.44.0). cc: @kennylam @jeffchew

**Comment by AndaPatrascu** [comment] 2023-02-22 14:35
@proeung Hi, thank you for your feedback on this. The timeline for 28th March is too long indeed, we need this on a priority. If a patch is possible, that would be great. Let me know if we can proceed with it and if I can help in any way.

**Comment by jeffchew** [comment] 2023-02-23 18:01
Hi @AndaPatrascu , 

Patch releases are typically reserved for severity 1 bug fixes and not introducing major functionality and enhancements.

**Closed** 2023-03-01 15:25 UTC
Labels: bug, severity 2, dev, package: web components, owner:  Innovation Team

**Comment by AndaPatrascu** [comment] 2023-03-01 17:05
@m4olivei @proeung @jeffchew Hi team, is this solved or just moved into another ticket? Thank you.

**Comment by kennylam** [comment] 2023-03-01 18:29
It's been resolved in #10085 and will be included in the next release.

**Comment by proeung** [comment] 2023-03-01 18:40
@AndaPatrascu To piggyback on what @kennylam mentioned above, the fixes for this issue will be included in the `v1.45.0` release, which has a full release date of **Mar 28, 2023**. The full release will include updates to the `lastest` tag CDN file that the `/cloud` web segment is currently adopting (https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/latest/cloud-masthead.min.js).

Also, for the testing of the C4IBM `v1.45.0` release, our QA team will be switching the CDN reference within the Drupal admin settings (`/admin/config/utilities/web-components`) to the `next` tag (https://1.www.s81c.com/common/carbon-for-ibm-dotcom/tag/v1/next/cloud-masthead.min.js) to ensure that there's no regression.
