### ISSUE TITLE
[Link with icon] Web components: icon position when text wraps to 2 lines 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-for-ibm-dotcom#5705] opened 2021-04-05 15:15 UTC
Currently link with icon is not showing the correct behavior when link text wraps to 2 lines. Icon snaps to right-aligned to the container, and creates a weird gap between text and icon. This could happen when text is too long, or when screen size is narrow, and is influencing several dependent components such as `Link list`, `Link list section`, and `Content group banner`

This is similar problem to (#5740 )

#### Current

![Apr-02-2021 16-52-42.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/daeba0c3-fb50-4005-8468-6913d6923c9d)

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/7d7a419e-8c4d-42e1-9050-d6f371b4cf06)

## Proposed design & spec

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/28c55ded-f65e-4a13-abf5-92216e57dcbd)

**Comment by jeffchew** [comment] 2021-07-29 14:57
@kennylam going to unassign this from you since you're on vacation for the rest of the sprint, and I want you to focus on Beacon next sprint.

**Comment by emyarod** [comment] 2021-07-30 19:07
@shixiedesign just want to clarify some of the text wrap behavior I'm currently testing, does this recording match the expected behavior outlined in the spec? depending on the viewport size the icon can wrap to the next line before the last word does

https://user-images.githubusercontent.com/8265238/127699900-c8084648-3f9c-40db-b1bd-6ee8aeaf5fc8.mov

**Comment by shixiedesign** [comment] 2021-08-02 17:43
Hey @emyarod yep that is the expected behavior. Unfortunately there are awkward moments (when 1 arrow breaks to line 2 before the other one). 

I think if there's possibility to have an "orphan" logic so the arrows is always gonna be attached to 1 word with it, it could be nice. Lemme know if that's even possible. If so, I can add a feature request for the team to look at.

**Comment by emyarod** [comment] 2021-08-03 13:54
that behavior is tricky but should be possible (although it may be a breaking change). I will need to test more and see if it can be implemented with minimal changes to the existing component

**Comment by RobertaJHahn** [comment] 2021-08-09 21:03
Bug must also be fixed in React.  Issue (#6837 ) has been created to manage that work.

**Closed** 2021-08-09 21:04 UTC
Labels: bug, severity 3, dev, package: web components
