### ISSUE TITLE
[ui-shell]: Sync UI Shell component and story to Carbon core

### ISSUE THREAD

**Issue by annawen1** [carbon-design-system/carbon-for-ibm-dotcom#9891] opened 2023-01-09 19:05 UTC
### The problem

The @carbon/web-components ui-shell component is behind in functionality, it should be updated to match what is currently on Carbon core's React UI-Shell: https://react.carbondesignsystem.com/?path=/story/components-ui-shell--header-base-w-actions-and-switcher

### The solution

Update @carbon/web-components' ui-shell component and stories to sync with Carbon core

### Application/website

N/A

### Business priority

Medium Priority = upcoming release but is not pressing

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment] 2023-02-23 19:26
Dupe of #9894

**Closed by kennylam** 2023-02-23 19:26 UTC
Labels: Feature request
