### ISSUE TITLE
[Masthead/Footer] Accessibility - unique labels for navigation elements

### ISSUE THREAD

**Issue by kyjak** [carbon-design-system/carbon-for-ibm-dotcom#6025] opened 2021-05-11 11:30 UTC
Multiple elements with "navigation" role do not have unique labels
Each element with "navigation" role must have a unique label that describes its purpose
please note when adding labels, these need to be translated to all DOCS languages, we can help with that,
and include the label in our translation request.

`<nav class="bx--legal-nav">`

**Comment by kyjak** [comment] 2021-05-12 07:13
you can use our dev https://ibmdocs-dev.mybluemix.net/docs/en
and the tool to check errors is "IBM Equal Access Accessibility Checker", plugin for chrome

**Comment by jeffchew** [comment] 2021-05-27 12:52
@Praveen-sr can you review?

**Comment by jeffchew** [comment] 2021-07-29 16:08
SDMA squad has also reported this, but for web components. Added label to the issue.

**Comment by Praveen-sr** [comment] 2021-08-02 12:49
Ram's comments:
Duplicate of [#6023](https://app.zenhub.com/workspaces/carbon-for-ibmcom-5d449f3642eb1962336cbe52/issues/carbon-design-system/carbon-for-ibm-dotcom/6024)

Footer default - Landmark region ( On JAWS FF & iPhone Voiceover)
Issue: Found 2 navigation region and one complimentary region with in the footer section . Which is not needed.
Expected: Avoid resentence or give the first as primary navigational links and second one as secondary navigation.
@jeffchew @RobertaJHahn

**Closed** 2021-09-02 18:48 UTC
Labels: bug, package: react, severity 4, dev, accessibility, adopter support, adopter: KC, package: web components
