### ISSUE TITLE
React: Masthead - issue related to user profile menu

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4197] opened 2020-10-09 11:44 UTC
## Detailed description

Issue: 
1. After expanding the user profile button 
for the screen reader user the focus remains on the triggering control itself  when we use arrow key immediately to navigate through the options, even though visually it is available after the user profile button for screen reader user it is available before the end of  main region.
2. When  we use arrow key navigate through the options, Screen reader is identifying ""link focus sentinel "" before and after the my IBM menu and log in menu , 
Note: the mentioned link  is not visually available and also after activation no action happened..

Expected: 
1. Screen reader should identify the options immediately after the triggering element.
2. if the user is suppose to interact with the mentioned link make it available for both sighted as well as screen reader users otherwise hide the mentioned link from the screen reader users as well.

**Comment by kennylam** [comment] 2020-11-10 20:24
Duplicate of #4233

**Closed by kennylam** 2020-11-10 20:24 UTC
Labels: Airtable Done, Sprint Must Have, accessibilty, bug, dev, package: react, severity 2
