### ISSUE TITLE
[Pagination component]: Pagination page size

### ISSUE THREAD

**Issue by cedricpelle** [carbon-design-system/carbon-for-ibm-dotcom#9968] opened 2023-01-30 15:22 UTC
### Description

Hi 
I have a strange behavior with the Data Table / Pagination
The page size is always 10 even i set other

![image](https://user-images.githubusercontent.com/38075847/215517260-78c1fde0-029f-44b1-9a9f-7e02311dad74.png)

it is the html code that i am using 
<bx-pagination page-size="25" start="0" total="99"><bx-page-sizes-select slot="page-sizes-select"> <option value="10">10</option> <option value="25">25</option> <option value="50">50</option> <option value="100">100</option> </bx-page-sizes-select> <bx-pages-select></bx-pages-select></bx-pagination>

I am using
https://1.www.s81c.com/common/carbon/web-components/version/v1.21.0/pagination.min.js

Range is ok i have 1-25 of 99 Items
Number of page too is good

On the codesanbox of the datatable, same issue
https://codesandbox.io/s/github/carbon-design-system/carbon-web-components/tree/main/examples/codesandbox/basic/components/data-table

### Component(s) impacted

Pagination

### Browser

Firefox

### Carbon for IBM.com version

1.21.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

IBM terms

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://codesandbox.io/s/github/carbon-design-system/carbon-web-components/tree/main/examples/codesandbox/basic/components/data-table

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by IgnacioBecerra** [comment] 2023-01-31 23:30
Cannot reproduce -- feature works as intended. Closing issue.

**Closed by IgnacioBecerra** 2023-01-31 23:30 UTC
Labels: bug, dev
