### ISSUE TITLE
Reboot requested changes to Content group - pictograms and Pictogram item

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#2560] opened 2020-05-27 21:21 UTC
### The problem
_We want the pictogram item text to visually align with all other text in it's group and block. This is currently challenging because the text inside pictogram item is only spanning 90% of a 6 column container (because of being indented 2 columns by the pictogram) and all other text is spanning 90% of an 8 column container. _

### The solution
_Have the entire pictogram item (pictogram + text) span 90% of 8 columns so that it will properly align with other text above and below it that is 90% of the 8 column container._

### Additional information
- Reboot provided designs
 -Content group with pictograms Box folder link:  https://ibm.ent.box.com/folder/94758548768
 -Pictogram item:  https://ibm.ent.box.com/folder/101184830347

**Comment by oliviaflory** [comment] 2020-08-07 18:58
@andysherman2121 I got some clarification from Lila

>Because we are using percentages we need the entire pictogram item to span 90% of the container not just the text. 2 column picto + 90% of 6 columns will not align with 90% of 8 columns

The problem is the pictogram text is extending further than other text in other patterns, like we see in [Content block mixed](https://ibmdotcom-react.mybluemix.net/iframe.html?id=components-contentblockmixed--default). screen shot below:

<img width="677" alt="Screen Shot 2020-08-05 at 1 02 16 PM" src="https://user-images.githubusercontent.com/45692622/89456276-9fa54800-d731-11ea-86e4-e9b35fdebe86.png">

**Comment by jeffchew** [comment] 2020-08-14 15:31
@RobertaJHahn moving this out to the next release.

cc: @andysherman2121

**Comment by RobertaJHahn** [comment] 2020-08-14 18:41
Airtable updated.

**Comment by RobertaJHahn** [comment] 2020-10-09 20:27
@andysherman2121 Moved out to the next release and sprint.

**Closed** 2020-11-06 14:13 UTC
Labels: Airtable Done, Feature request, adopter: Drupal, dev, package: react, priority: low
