### ISSUE TITLE
[Bug]: Overflow menu not positioning correctly

### ISSUE THREAD

**Issue by aaronmg241** [carbon-design-system/carbon-for-ibm-dotcom#11408] opened 2024-01-15 19:15 UTC
### Package

carbon-components

### Browser

Chrome

### Package version

v1.28

### React version

Using web components, not react.

### Description

When I click an overflow menu, it seems that the position (top attribute specifically) of the menu body is not calculated correctly. I have tried different version of the Webcomponents V1 Overflow Menu and none seem to position the menu correctly.

![image](https://github.com/carbon-design-system/carbon/assets/93608123/c96f13e8-2cee-495c-90da-d6db1f830e69)

### Reproduction/example

https://codesandbox.io/p/sandbox/naughty-curran-rx95n3?file=%2Findex.html

### Steps to reproduce

Click overflow menu button. Overflow menu appears far below button.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by kennylam** [comment] 2024-01-22 15:49
Duplicate of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9827

**Closed by kennylam** 2024-01-22 15:49 UTC
Labels: bug, package: carbon web components
