### ISSUE TITLE
[ContentBlock components] Storybooks QA

### ISSUE THREAD

**Issue by DragosRistici** [carbon-design-system/carbon-for-ibm-dotcom#5533] opened 2021-03-18 11:09 UTC
## [Content block cards] general issues - from both Web components and React Storybooks

Please, rename it in both Storybooks, from this: 
<img width="197" alt="Screenshot 2021-03-18 at 14 41 14" src="https://user-images.githubusercontent.com/48327647/111627762-16421200-87f8-11eb-9920-be8804604e9a.png">

to this:
```
Content block cards
    Default
    With images
    With videos
```

Rename the themes by their full name, from this: 
<img width="359" alt="Screenshot 2021-03-18 at 14 43 31" src="https://user-images.githubusercontent.com/48327647/111627967-5608f980-87f8-11eb-9bf4-c0424146bd65.png">

to this:
```
White
Gray 10
Gray 90
Gray 100
```

and also add this, but change the first one to `Container bottom border` and make the options be: `With border` and `Without border`. Make the first one selected by default: 
<img width="635" alt="Screenshot 2021-03-17 at 15 30 43" src="https://user-images.githubusercontent.com/48327647/111521957-6bcbdf80-8762-11eb-8946-0c1384c4c4a1.png">

1. Make sure to apply a max-width of 320px or 4 columns to the CTA card link on all 4 themes and all break points.

<img width="670" alt="card max width" src="https://user-images.githubusercontent.com/48327647/111623236-c57bea80-87f2-11eb-8f76-192536767669.png">

2. At max break point, card height is wrong.
<img width="773" alt="Screenshot 2021-03-18 at 14 06 41" src="https://user-images.githubusercontent.com/48327647/111623633-49ce6d80-87f3-11eb-844d-a659c0e74dd4.png">

3. At xlg break point, the cards are 319px X 320px. Is that by design, so you can add that border? 
<img width="347" alt="Screenshot 2021-03-18 at 14 21 24" src="https://user-images.githubusercontent.com/48327647/111625190-3fad6e80-87f5-11eb-9d2a-ef6b5fa67c1d.png">

4. Apply the max-width of 640px or the width= calc(8 col – $layout-03) istead of percentages dependant width.
<img width="1337" alt="Screenshot 2021-03-18 at 14 28 54" src="https://user-images.githubusercontent.com/48327647/111626129-4dafbf00-87f6-11eb-9f4f-68dea8ac0337.png">

5. At md break point, the cards are on 2 columns instead of 4: 
<img width="727" alt="Screenshot 2021-03-18 at 14 31 59" src="https://user-images.githubusercontent.com/48327647/111626515-cadb3400-87f6-11eb-98bb-9c149d11278f.png">

6. The same for the CTA card link, as seen below:
<img width="696" alt="Screenshot 2021-03-18 at 14 34 30" src="https://user-images.githubusercontent.com/48327647/111626857-20174580-87f7-11eb-93b8-d260dd7e343f.png">

On the React Storybook, it has the wrong dimensions also:
<img width="682" alt="Screenshot 2021-03-18 at 14 36 13" src="https://user-images.githubusercontent.com/48327647/111627092-64a2e100-87f7-11eb-958b-e7569c47acbd.png">

7. On mobile, the card groups have, again, 319px X 320px, and the CTA card link is not respecting the max-width of 320px. 
<img width="388" alt="Screenshot 2021-03-18 at 14 38 43" src="https://user-images.githubusercontent.com/48327647/111627632-ec88eb00-87f7-11eb-9ae6-36a71b16c48f.png">

8. Same title height does not work
<img width="910" alt="Screenshot 2021-03-18 at 16 11 41" src="https://user-images.githubusercontent.com/48327647/111640314-c0c03200-8804-11eb-8c5f-a3936d1829c8.png">

## Detailed description

> Describe in detail the issue you're having.

> Is this a feature request (new component, new icon), a bug, or a general
> issue?
Bugs
> Is this issue related to a specific component?
Content block – with cards
> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome
> What version of Carbon for IBM.com are you using?
Latest
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by kennylam** [comment] 2021-07-08 21:15
@DragosRistici This issue is addressed in #6598, with a few notes:

- [ ] 1. Make sure to apply a max-width of 320px or 4 columns to the CTA card link on all 4 themes and all break points.
- [ ] 2. At max break point, card height is wrong.
  - Here you reference the card height, but have the heading selected. Assuming you meant to select the card element, is there a minimum height for the card when there is very little copy?
- [ ] 3. At xlg break point, the cards are 319px X 320px. Is that by design, so you can add that border?
  - correct
- [ ] 4. Apply the max-width of 640px or the width= calc(8 col – $layout-03) istead of percentages dependant width.
  - This should be done at the `content-block` level so all `content-block-*` components get the change.
- [ ] 5. At md break point, the cards are on 2 columns instead of 4
- [ ] 6. The same for the CTA card link, as seen below
- [ ] 7. On mobile, the card groups have, again, 319px X 320px, and the CTA card link is not respecting the max-width of 320px.
  - same as #&#x2060;3
- [ ] 8. Same title height does not work
  - Editing the copy after the page is loaded will not trigger the `sameHeight` utility, so the headings will be different heights. The heading heights are evaluated on page load only. You can see an example of it working correctly [here](http://ibmdotcom-web-components-canary.mybluemix.net/?path=/story/components-card-group--default).

**Comment by DragosRistici** [comment] 2021-07-20 08:29
This one depends on #6606 which will be addressed in sprint 15.

**Comment by jeffchew** [comment] 2021-08-04 16:44
To update this, the issue is now unassigned and ready to be picked up again. The PR mentioned above was closed without merging.

@kennylam can provide guidance on the work needed to get this story completed.

FYI: @shixiedesign @RobertaJHahn @DragosRistici

**Closed** 2021-10-11 13:13 UTC
Labels: bug, severity 3, dev, storybook
