### ISSUE TITLE
[leadspace-with-search]: (react wrapper) image not appearing

### ISSUE THREAD

**Issue by ariellalgilmore** [carbon-design-system/carbon-for-ibm-dotcom#8289] opened 2022-02-15 17:17 UTC
### Description

the leadspace with search with image story does not show any image
<img width="366" alt="Screen Shot 2022-02-15 at 10 05 55 AM" src="https://user-images.githubusercontent.com/20210594/154114240-df0d1412-804c-417b-993f-68722efea641.png">

### Component(s) impacted

LeadspaceWithSearch

### Browser

Chrome

### Carbon for IBM.com version

1.31.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

carbon for ibm.com

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-lead-space-search--with-image

### Steps to reproduce the issue (if applicable)

1. go to https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components-react/?path=/story/components-lead-space-search--with-image
2. look for image

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment] 2022-03-18 14:48
This issue looks to be a duplicate of this one https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8308

**Closed by proeung** 2022-03-18 14:49 UTC
Labels: bug, severity 3, dev, package: web components
