### ISSUE TITLE
[Masthead] Focus goes to the hidden element - DDS Consulting

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#5895] opened 2021-04-26 08:30 UTC
## Detailed description

Issue:
Doing tab key from IBM logo focus goes to the menu items which is hidden because of the open search edit field.

Expected:
Doing tab key navigation from the IBM logo focus should go to the open search field, not on the hidden menu items.

## Additional information
- 

----
- Hybrid Cloud developer: 
- HC Jira ticket:
- DDS consultant:

**Comment by proeung** [comment] 2021-08-30 21:17
@Praveen-sr Can you provide a video screenshot of the issue you're seeing? Thanks!

**Comment by annawen1** [comment] 2021-08-31 15:18
@Praveen-sr not able to replicate this, could you re-test?

**Comment by annawen1** [comment] 2021-09-09 14:22
@Praveen-sr has re-tested and is not able to reproduce anymore - will close this ticket.

**Closed by annawen1** 2021-09-09 14:22 UTC
Labels: bug, severity 3, dev, accessibility, package: web components, owner:  Hybrid Cloud
