### ISSUE TITLE
Web component - link with icon - Icon placement from right to left does not change position.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#7867] opened 2021-12-13 13:47 UTC
### Description

Issue: 
link with icon - Icon placement from right to left does not change position.

### Component(s) impacted

![image](https://user-images.githubusercontent.com/60002341/145823698-ef01fe80-efcd-465d-befc-72d12cdf6ed7.png)

### Browser

Chrome, Safari, Firefox

### Carbon for IBM.com version

1.28

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

Web component

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

NA

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by emyarod** [comment] 2021-12-13 15:03
may be a duplicate of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7074

**Comment by RobertaJHahn** [comment] 2021-12-14 13:38
Closing.  Based on Andrew's comments above

**Closed by RobertaJHahn** 2021-12-14 13:38 UTC
Labels: bug, severity 2, dev, package: web components
