### ISSUE TITLE
Component: LightboxMediaViewer and CTA - greyed out scrollbar is displayed on ratio 2:1 (1024*512)

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#2460] opened 2020-05-20 07:35 UTC
## Detailed description

Device : Windows 
Browser : Chrome

Issue on LightboxMediaViewer and CTA sections.

Issue :- Scroll bar is displayed on ratio 2:1 (1024*512),  which is not required.

Expected : When the copy text is large the scroll option must be activated.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/33e66959-8606-4c72-b5af-0698b84f6648)

**Comment by kennylam** [comment] 2020-05-21 15:17
@Praveen-sr Which storybook environment are you seeing this on? I tried both below and cannot reproduce in Windows Chrome.

http://ibmdotcom-react.mybluemix.net/?path=/story/components-lightboxmediaviewer--default

http://ibmdotcom-react-staging.mybluemix.net/?path=/story/components-lightboxmediaviewer--default

**Comment by RaphaelAmadeu** [comment] 2020-07-24 21:00
This issue is happening due to `overflow`, as it's set to auto, it's going to have some resolutions that will display a blank scrollbar, I don't know if this is a bug by itself.

cc: @kennylam @jeffchew

**Comment by NSDrowned** [comment] 2021-03-09 02:22
Hello @Praveen-sr, does this issue still apply? I tested but couldn't reproduce.

**Comment by NSDrowned** [comment] 2021-03-11 06:10
Hello @Praveen-sr, any update on this one?

**Comment by Praveen-sr** [comment] 2021-03-23 11:34
@NSDrowned Re tested this on web components staging, still the issue exists. Scroll bar appears for 2:1 ratio

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/a8d92abe-5401-4b12-9080-4c199533cc1c)

On React for 2:1
![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/f301f864-09b8-496f-abe4-ccc85954068d)

CC @RobertaJHahn

**Comment by RobertaJHahn** [comment] 2021-04-23 20:21
Closing based on the comments in the PR 5640.  Not a suitable fix.

**Closed by RobertaJHahn** 2021-04-23 20:21 UTC
Labels: Airtable Done, QA, bug, dev, package: react, severity 3
