### ISSUE TITLE
[locale-modal-flashing]: The locale modal is flashing when the page is loading

### ISSUE THREAD

**Issue by paatsinsuwan** [carbon-design-system/carbon-for-ibm-dotcom#7943] opened 2022-01-07 02:02 UTC
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2386
- DPO consulting engineer: @IgnacioBecerra 

-----

### Description

Locale modal is flashing when refresh the page while it should not

[video](https://ibm.box.com/v/modal-flickering-bug)

### Component(s) impacted

dotcom-shell
locale-modal

### Browser

Firefox, Chrome

### Carbon for IBM.com version

^1.14.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Application/website

NDA

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template

### Steps to reproduce the issue (if applicable)

Clone template https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template
Run `yarn start` (might have to fiddle with webpack-dev-config.js)
After the page load, hit refresh and wait

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by ljcarot** [comment] 2022-01-10 16:34
@paatsinsuwan the link to video in Box does not work for me.

**Comment by paatsinsuwan** [comment] 2022-01-12 13:37
@ljcarot I've updated the link to the video and also here https://ibm.box.com/v/modal-flickering-bug.

**Comment by jeffchew** [comment] 2022-01-24 20:30
@proeung adding @IgnacioBecerra to the issue. He mentioned he may know the cause of this issue.

**Comment by IgnacioBecerra** [comment] 2022-01-24 21:12
@paatsinsuwan The video seems to be unavailable, but this issue might be fixed in `v1.30.0-rc1`. Could you test with the new release? If it's not fixed I might have another solution for this. Let me know!

**Comment by paatsinsuwan** [comment] 2022-01-24 21:56
@IgnacioBecerra I just ran `yarn update-canary` and I'm still seeing the flash. 
  
https://user-images.githubusercontent.com/910956/150871473-1921ac41-6fc7-4403-9391-76628fccd6c7.mov

**Comment by IgnacioBecerra** [comment] 2022-01-31 23:28
@paatsinsuwan Would you be able to share your repo? I can't seem to replicate the error on my local machine.

**Comment by andy-blum** [comment] 2022-02-02 14:01
@paatsinsuwan I'm also unable to replicate based on the steps you provided in the issue description. Is this issue still occuring with the latest changes to the template repo?

**Comment by paatsinsuwan** [comment] 2022-02-03 21:25
@IgnacioBecerra @andy-blum Confirm that the issue is no-longer happening.  But I do have to re-clone the template to get it to work as expected.  Thank you both.

**Comment by hongyuxgt** [comment] 2022-02-07 07:39
@IgnacioBecerra @andy-blum It looks like the same issue happened in component(footer-container), would you please help to check？
import "@carbon/ibmdotcom-web-components/es/components/footer/footer-container.js"

**Comment by kennylam** [comment] 2022-03-28 18:03
Issue still occurs in FF as of `v1.31.1`.

**Comment by kennylam** [comment] 2022-04-08 17:43
@paatsinsuwan Is there a site where this is happening you can share? A number of us have tried to reproduce this and cannot.

**Comment by paatsinsuwan** [comment] 2022-04-08 17:59
@kennylam I can still see it with the latest version of this template.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template

**Comment by kennylam** [comment] 2022-04-08 18:45
Got it, we'll take a look. Thanks!

**Comment by andy-blum** [comment] 2022-04-08 19:25
@paatsinsuwan Can you link something live other than the github repo? We've looked at that template following the steps to reproduce in the issue description and have not been able to reproduce.

**Comment by paatsinsuwan** [comment] 2022-04-08 19:27
@andy-blum have you tried in FF?  I'm pretty sure you'll see it.

**Comment by andy-blum** [comment] 2022-04-08 19:41
@paatsinsuwan Yes, we tried firefox.

Here's what I did:
1. Open project in gitpod using this link: https://gitpod.io/#https://github.com/carbon-design-system/carbon-for-ibm-dotcom-web-components-template
2. Wait for project to build and start. When the process is ready it should pop up an alert allowing you to open the preview
<img width="1440" alt="Screen Shot 2022-04-08 at 3 36 35 PM" src="https://user-images.githubusercontent.com/25532785/162515103-21b61912-b3bd-4316-9661-69c340ade0d0.png">
3. If that banner doesn't appear or you miss it, you can open the preview from the sidebar (1). The globe icon (2) will launch the preview, but it will be private by default, requiring you to be authenticated in the browser. You can make the preview public with the unlock icon (3)
<img width="350" alt="Screen Shot 2022-04-08 at 3 37 33 PM" src="https://user-images.githubusercontent.com/25532785/162515428-2b3419d3-0752-422b-ad27-a4950a7d6716.png">

Using the above process, I was unable to replicate the flashing issue, and @kennylam @ariellalgilmore and @annawen1 also confirmed they were unable to see the flash.

**Comment by paatsinsuwan** [comment] 2022-04-08 19:49
@andy-blum Hey man, if you confirmed it fixed, I'll take it.

**Comment by kennylam** [comment] 2022-04-08 21:09
Thanks @andy-blum!

**Closed by kennylam** 2022-04-08 21:09 UTC
Labels: bug, package: react, severity 3, dev, adopter support, package: web components
