### ISSUE TITLE
[skip-to-content]: A11y - Hyperlink has no link text, label or image with a text alternative

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/carbon-for-ibm-dotcom#8761] opened 2022-04-28 15:46 UTC
### Description

Web components `skip-to-content` requires an `aria-label`.

![image](https://user-images.githubusercontent.com/909118/165792034-ff0e87f4-134a-4b85-8956-2ad9eb75e9cd.png)

### Component(s) impacted

`skip-to-content`

### Browser

Chrome

### Carbon for IBM.com version

v1.21.0

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

Carbon for IBM.com

### Package

@carbon/carbon-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/iframe.html?id=components-masthead--default

### Steps to reproduce the issue (if applicable)

Go to site provided. Run IBM Equal Access checker

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by andy-blum** [comment] 2022-12-22 17:55
Duplicate of #8759

**Closed by andy-blum** 2022-12-22 17:55 UTC
Labels: bug, dev, accessibility, package: carbon web components
