### ISSUE TITLE
[Tabs extended with media]: accordion overlaps tab content title

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#9266] opened 2022-08-18 14:12 UTC
### Description

The tabs extended with media tab heading is getting overlapped by the hover state of the accordion 

user can still read the title in default state 

<img width="677" alt="Screen Shot 2022-08-18 at 10 03 23 AM" src="https://user-images.githubusercontent.com/45692622/185416333-337d34b5-9865-4d19-8e79-4c14747bf3c0.png">

### Component(s) impacted

tabs extended with media

### Browser

Chrome

### Carbon for IBM.com version

v1.21.0

### Severity

Severity 4 = The problem is not visible to or noticeable to an average user. Affects minor functionality, no workaround needed.

### Application/website

C4DOTCOM

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://www.ibm.com/standards/carbon/web-components/?path=/story/components-tabs-extended-with-media--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by kennylam** [comment] 2022-10-12 19:08
Looks like a duplicate of #8318

**Closed by kennylam** 2022-10-12 19:08 UTC
Labels: bug, dev, hacktoberfest
