### ISSUE TITLE
Masthead-l1 title and Masthead-l0 platform are different

### ISSUE THREAD

**Issue by guilhermelMoraes** [carbon-design-system/carbon-for-ibm-dotcom#4145] opened 2020-10-06 18:02 UTC
## Detailed description

The masthead-l1 has a `title` property:
<img width="1591" alt="Screen Shot 2020-10-06 at 12 47 04" src="https://user-images.githubusercontent.com/42848561/95225350-17473000-07d2-11eb-9f10-2f20bb266061.png">

The masthead-l0 has an optional `platform` property:
<img width="1576" alt="Screen Shot 2020-10-06 at 12 48 31" src="https://user-images.githubusercontent.com/42848561/95225555-4cec1900-07d2-11eb-9db5-4028af9a3238.png">

This is more like a question: they're not the same thing? They have pretty much the same behavior, which is to redirect the user to the l0 page of the `title`/`platform`.

> Is this issue related to a specific component?

[Masthead-l0 with platform](http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--default) and [Masthead-l1 with title](http://ibmdotcom-react-canary.mybluemix.net/?path=/story/components-masthead--with-l-1).

> What would you like to see changed?

The `title` property appears at the hamburger menu (`MastheadLeftNav`).

> What version of the IBM.com Library are you using?

Canary, updated last week.

## Additional information

This question came up after Praveen opened a [bug at the Services page board](https://github.ibm.com/ibm-com-reboot/services-page/issues/40). The current `title` from L1 doesn't appear in the hamburger menu for the `md` breakpoint and bellow, as we would like to happen.

**Comment by kennylam** [comment] 2020-10-07 15:44
@guilhermelMoraes The original design specs did not treat these the same. The platform name exists only in the L0, whereas `Services & Consulting` in your example is the top-level page for that section, which is not the same as platform.

@oliviaflory @wonilsuhibm is this correct, unless something has changed?

**Comment by oliviaflory** [comment] 2020-10-07 18:46
I am honestly not sure @kennylam, the L1 was switch to what Gui is showing from what Lara originally designed (the dark L1)

I didn't get a chance to look into how the two relate before it was implemented, but I believe the idea is if there is an L1 there will not be any links in the L0.

**Comment by wonilsuhibm** [comment] 2020-10-13 13:05
Eventually, they may become the same thing, but for now, we should treat them as two separate things.

**Comment by RobertaJHahn** [comment] 2020-10-13 13:29
Closing because this is working as designed.

**Closed by RobertaJHahn** 2020-10-13 13:29 UTC
Labels: bug
