### ISSUE TITLE
Design Kit:  Add the Carbon Expressive components to the ibm.com Library Design Kit

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/carbon-for-ibm-dotcom#3443] opened 2020-08-05 14:46 UTC
This epic contains the scope definition of the deliverable. This epic also includes links to all of the work required to deliver the component.

#### Additional Information
- Carbon Expressive components themes:
- [ ] White Theme
- [ ] Gray 10
- [ ] Gray 90
- [ ] Gray 100
-

**Comment by oliviaflory** [comment] 2020-10-29 14:27
Closing this epic, expressive design kits have been released, this is a duplicate of another epic

**Closed by oliviaflory** 2020-10-29 14:27 UTC
Labels: design, epic
