### ISSUE TITLE
[Web-components]: tabs not highlight current selected tab

### ISSUE THREAD

**Issue by korgan00** [carbon-design-system/carbon-for-ibm-dotcom#11147] opened 2023-11-15 16:16 UTC
### Description

The current tab is not correctly highlighted, the border-bottom color doesn't have the correct color:
The Storybook is correctly showing the color but I cannot reproduce it in my project. I created a reproduction of the bug in  stackblitz.

Storybook:
![Captura de pantalla 2023-11-15 a las 17 03 23](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/0942788b-90bb-4b99-9132-cc1d03d3a4e0)

Stackblitz
![Captura de pantalla 2023-11-15 a las 17 04 34](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/4138279/2f108c9b-365f-4825-b261-d0dc258396d8)

Looking at the code in [this line](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/91e50fa5cfcd5a5b4950ad09bc76cc89b1dc09e0/packages/carbon-web-components/src/components/tabs/tabs.scss#L104) of the scss, the `[selected]` is appended to the tabs so the built selector is: 

`:host(cds-tabs)[selected]`. 

This is not a valid selector and it should be:

 `:host(cds-tabs[selected])`.

I confirmed the compilation with the compiled source in the navigator.

### Component(s) impacted

`tabs` and `tab`

### Browser

Chrome

### Carbon for IBM.com version

2.0.1

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

learning quantum platform

### Package

@carbon/web-components

### CodeSandbox example

https://stackblitz.com/edit/github-kqdr6r-5z4nqk?file=index.html

### Steps to reproduce the issue (if applicable)

Instantiate 2 tabs and select one.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by sangeethababu9223** [comment] 2023-11-22 10:37
Looks like the issue is not there while using CDN directly. Will look into this and update.

**Comment by siaikin** [comment] 2023-11-29 06:34
It seems to be an issue with this line of code.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/8031fcca05de52ae7519434beb5a80294491a06a/packages/carbon-web-components/src/components/tabs/tabs.scss#L102

@sangeethababu9223 Which branch should I contribute to for the @carbon/web-components package?

**Comment by sangeethababu9223** [comment] 2023-11-30 15:37
@siaikin,
Could you please move the PR to the main branch?

**Comment by siaikin** [comment] 2023-11-30 16:53
> @siaikin, Could you please move the PR to the main branch?

hi @sangeethababu9223 thanks you reply.

I'm sorry, I can't do this, the main branch and feat/cwc-v2 have huge differences in the tabs.scss file. It's not even certain whether the issue exists on the main branch. This is not a reasonable request.

Perhaps my understanding is incorrect?

> Currently, I am only requesting to merge this PR #11175 into feat/cwc-v2 based on my own guess.

**Comment by sangeethababu9223** [comment] 2023-12-01 07:17
> > @siaikin, Could you please move the PR to the main branch?
> 
> hi @sangeethababu9223 thanks you reply.
> 
> I'm sorry, I can't do this, the main branch and feat/cwc-v2 have huge differences in the tabs.scss file. It's not even certain whether the issue exists on the main branch. This is not a reasonable request.
> 
> Perhaps my understanding is incorrect?
> 
> > Currently, I am only requesting to merge this PR #11175 into feat/cwc-v2 based on my own guess.
> 
> a new pr #11181 with merge to `main`

Creating a new PR works! Thanks!
"feat/cwc-v2" and some other branches are being deleted and these branches have been merged to main.

**Comment by abdonrd** [comment] 2024-01-05 16:18
@sangeethababu9223 any ETA to review the @siaikin PR? Thanks! 🙏

**Closed** 2024-02-01 18:08 UTC
Labels: bug, dev, package: carbon web components
