### ISSUE TITLE
cta-section: additional spacing problem

### ISSUE THREAD

**Issue by skycryer** [carbon-design-system/carbon-for-ibm-dotcom#9167] opened 2022-07-22 12:46 UTC
**Engineering info:**  
- Innovation Team engineer: 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/ADCMS-2476
- DPO consulting engineer: N/A

-----

### Description

The cta setion has extra spacing and fixed height for the items. With this spacing there is some more spacing then it should
<img width="1204" alt="Screenshot 2022-07-22 at 14 34 21" src="https://user-images.githubusercontent.com/3725699/180441324-91214335-eb20-47df-8851-5a0a4eef2a2f.png">
Fixed item height

<img width="1204" alt="Screenshot 2022-07-22 at 14 34 39" src="https://user-images.githubusercontent.com/3725699/180441355-7b9590dd-ee95-4fe3-8139-55755d87aa31.png">
Extra spacing below component.

### Component(s) impacted

cta-section

### Carbon Web Components version

1.20.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Application/website

IBM CMS

### CodeSandbox example

https://prod-author.roks.cms.cis.ibm.net/content/adobe-cms/language-masters/en/products/watson-orchestrate.html?wcmmode=disabled

### Steps to reproduce the issue (if applicable)

Just add this component over another component. THen you see the component has to much empty spacing below

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

**Comment by kennylam** [comment] 2022-07-26 13:56
The heights on content items should be moved off the `sameHeight` utility and utilize `css-grid` instead. This would solve the problem of fixed heights that are too tall for smaller amounts of content and remove the requirement for `min-height`.

cc: @oliviaflory We should consider creating an audit for all components using `sameHeight` and refactoring them to use `css-grid` instead.

**Comment by proeung** [comment] 2022-08-09 15:57
@oliviaflory @jwitkowski79 Does this ticket fall under the spacing auditing effort that you guys have been discussing, especially related to the specs coming from the branding expression work as well as whether to expose spacing prop for adopters to pick and choose?

**Comment by skycryer** [comment] 2022-08-19 06:33
Should this be fixed with carbon 1.37? Because i can still see the spacing issues

**Comment by jkaeser** [comment] 2022-08-29 14:37
## Incorrect spacing

> This issue looks to be more appropriate on the C4IBM repo side. Would it be okay, if I move it there or are there a way to see issues from this `carbon-web-components` repo on the `carbon-for-ibm-dotcom` side as well?

@proeung I'm finding evidence that this issue is caused by the adopter's code. A minified stylesheet originating from AEM is applying each of the styles shown in this screenshot:

<img width="1919" alt="Screen Shot 2022-08-29 at 9 38 12 AM" src="https://user-images.githubusercontent.com/12532727/187218081-9024f51e-7304-4cdd-9b6e-0489f2414734.png">

Everything looks closer to correct once those styles are disabled:

<img width="1919" alt="Screen Shot 2022-08-29 at 9 41 41 AM" src="https://user-images.githubusercontent.com/12532727/187218615-ca9a67ed-f38f-4c78-8cd5-4d5bc230c6c9.png">

I believe the only lingering issue is that the content items are a bit too tall, and this can also be explained.

## Content items too tall

> The heights on content items should be moved off the sameHeight utility and utilize css-grid instead. This would solve the problem of fixed heights that are too tall for smaller amounts of content and remove the requirement for min-height.

@kennylam It doesn't look like the `sameHeight` utility is forcing too much height here. Rather, a rogue `<p>` element is adding extra height to the calculation.

<img width="1919" alt="Screen Shot 2022-08-29 at 9 49 53 AM" src="https://user-images.githubusercontent.com/12532727/187217945-25f60943-efe3-4217-bcab-647cacca9fc5.png">

## Conclusion
It looks to me like the reported issues must be resolved within the adopter's application. Does anyone have a different take?

**Comment by proeung** [comment] 2022-09-13 15:24
@jkaeser Thanks for investigating this issue. If you and Kayle determined that this issue is coming from the adopter/AEM side, please go ahead and close out this issue and we can follow up the work in the JIRA ticket (https://jsw.ibm.com/browse/ADCMS-2476).

**Closed** 2022-09-13 16:00 UTC
Labels: Feature request, severity 4, adopter: AEM, owner:  Innovation Team, Needs design approval, follow-up: DDS engineering, follow-up: DDS design
