### ISSUE TITLE
IBM Web Standard Page links are broken

### ISSUE THREAD

**Issue by bmc-qnx** [carbon-design-system/carbon-for-ibm-dotcom#7163] opened 2021-09-16 01:37 UTC
Use the form below to report any bugs you find. Feel free to leave blank any sections that aren’t relevant but try to include as much detail as possible. The more details we have, the faster we can respond.

Describe the issue: 

> What did you expect to happen? What happened instead? 
I expected to be able to access the links for the various web standards IBM has. Instead I keep getting a site cannot be reached error.
> Component(s) impacted? Please include screenshots, or code and relevant URLs.
https://www.ibm.com/standards/web/
![image](https://user-images.githubusercontent.com/90809999/133534849-faa203e9-15f1-4d81-8e71-c2b1a9dbcf00.png)

> What browser(s)are you working in?
Google Chrome
> What version of Carbon for IBM.com are you using?

> What application/website do you work on? 

> Release date (if applicable):

Steps to reproduce the issue (if applicable):

1. Visit the https://www.ibm.com/standards/web/ page.
2. Click on any of the external links for web standards.
3. Receive an error similar to the above screenshot

Please provide any additional notes:

*Priority
High Priority = pressing release
Medium Priority = upcoming release but is not pressing
Low Priority = release date is not dependent on fix or not upcoming

**Comment by ljcarot** [comment] 2021-09-20 11:00
Links work for me. @bmc-qnx Are you an IBMer? or external?

**Comment by bmc-qnx** [comment] 2021-09-21 00:30
Business Partner.
I’m still unable to access the links. Apparently the DNS address cannot be found

**Comment by ljcarot** [comment] 2021-11-02 13:14
@bmc-qnx I am closing this issue as it is working as intended.  However, we will open an issue to add lock indicators to the links to indicate when that link goes to a page on the IBM VPN.  cc: @RobertaJHahn

**Closed by ljcarot** 2021-11-02 13:14 UTC
Labels: bug, adopter support, follow-up: adopter
