### ISSUE TITLE
React / Web component: Masthead L1 - In hamburger menu, platform name is not displayed.

### ISSUE THREAD

**Issue by Praveen-sr** [carbon-design-system/carbon-for-ibm-dotcom#4595] opened 2020-12-01 12:59 UTC
## Detailed description

On Mobile and Tab:
On react and web components

Issue: In hamburger menu, platform (Stock charts) name is not displayed.

## Additional information

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/ae90bcf5-3c22-40d6-8200-d124daa7ae52)

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/81dbf699-9935-4755-8e05-56b6219211f4)

**Expected:**

![image.png](https://images.zenhubusercontent.com/5e21a7b470118a498429a20e/31f9682d-b6f2-4005-b7d5-86748f37f097)

**Comment by guilhermelMoraes** [comment] 2020-12-02 14:12
@Praveen-sr I don't think this should be treated as a bug. We discussed this a month ago and looks like everything is fine. This issue ticket has the details: #4145 

@jeffchew @kennylam

**Comment by RobertaJHahn** [comment] 2020-12-03 20:40
Working as designed.  Closing.

**Closed by RobertaJHahn** 2020-12-03 20:40 UTC
Labels: Airtable Done, bug, dev, package: react, severity 2
