### ISSUE TITLE
[TOC - Default]: Web Components - TOC links navigate to a point where section titles are obscured in Mobile Chrome

### ISSUE THREAD

**Issue by QALosey** [carbon-design-system/carbon-for-ibm-dotcom#8271] opened 2022-02-14 21:57 UTC
**Engineering info:**  
- Innovation Team engineer: @andy-blum 
- Innovation Team JIRA Ticket: https://jsw.ibm.com/browse/HC-2402
- DPO consulting engineer: 

-----

### Description

Expected Results: 
  When viewing the TOC - Default component on Mobile Chrome, selecting a TOC link will direct the user to the relevant section of the page with the section headline displayed just below the page header.
 
Actual Results: 
  After selecting a TOC link in Mobile Chrome, the user is directed to the relevant section of the page, but at a point where the section headline is partially obscured by the page header.

### Component(s) impacted

Table of Contents - Default
![TOC - Android](https://user-images.githubusercontent.com/57540897/153952863-1f107831-1a56-4daf-9f59-fbc6a60e248d.jpg)

### Browser

Chrome

### Carbon for IBM.com version

v1.16.0-rc.1

### Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Application/website

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/

### Package

@carbon/ibmdotcom-web-components

### CodeSandbox example

https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-table-of-contents--default

### Steps to reproduce the issue (if applicable)

1. Open https://carbon-design-system.github.io/carbon-for-ibm-dotcom/next/web-components/?path=/story/components-table-of-contents--default on an Android device in Chrome browser
2. Select 'Canvas' to view the TOC web component
3. Open the drop down and select a content item
4.  Observe that the user is navigate to the relevant section of the page, but the section headline is partially obscured

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues) for duplicate issues

**Comment by proeung** [comment] 2022-02-15 14:52
@QALosey Thanks for opening this bug issue!

@annawen1 Could this issue be related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8240, where separation of the scrolling logic from the `dotcomshell` component should apply the correct offset position value?

**Comment by proeung** [comment] 2022-03-02 16:05
@andy-blum Can you take a look at this issue and see if the solution that you have for (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8240) is going to address this TOC overlapping issue that @QALosey noted above?

**Comment by andy-blum** [comment] 2022-03-02 19:29
@proeung @QALosey This isn't really a bug in the javascript. The issue is that the headings don't have the proper amount of padding/margin to prevent being overlapped.

### The component @QALosey linked to:

We can see the `<a>` element scrolls all the way to the top of the page as the `.scrollTo` code dictates, but the heading element doesn't have enough padding to pass the bottom of the ToC selector.

<img width="506" alt="Screen Shot 2022-03-02 at 2 22 34 PM" src="https://user-images.githubusercontent.com/25532785/156434418-b4f84644-0df0-4e08-b84a-f5706fe58003.png">

<img width="507" alt="Screen Shot 2022-03-02 at 2 22 45 PM" src="https://user-images.githubusercontent.com/25532785/156434699-78df0345-133e-4874-963f-2bcd6072a01a.png">


### The same component in the dotcom-shell

Again, the `<a>` is all the way at the top of the page, but the heading/content element has significantly more spacing above it.

<img width="788" alt="Screen Shot 2022-03-02 at 2 24 29 PM" src="https://user-images.githubusercontent.com/25532785/156434854-fc7bd3db-ca30-402e-986b-d859b3dbe9e5.png">

<img width="790" alt="Screen Shot 2022-03-02 at 2 24 49 PM" src="https://user-images.githubusercontent.com/25532785/156434862-ab7d79a5-82d6-422a-8e9d-11cff3d104b6.png">

I don't know if there are specific content guidelines around how to implement the ToC, but I don't think this requires a codefix.

**Comment by QALosey** [comment] 2022-03-08 21:15
@andy-blum @proeung So if no code fix is required, what should the next step be? Closing this ticket, and opening a new one regarding content guidelines and the need for additional padding/margin space for the headers when implementing a TOC?

**Comment by proeung** [comment] 2022-03-16 17:29
@kennylam @oliviaflory After speaking to our team, it looks like this issue is related to the TOC content headings where they don't have the proper amount of padding/margin to prevent being overlapped. Feels like this work might be better addressed by your team as you can indicate the proper spacing needed for the storybook preview side.

I'm going to take our Innovation team out of this issue and add you guys to it instead.

**Closed** 2022-03-31 14:49 UTC
Labels: bug, severity 3, dev, package: web components
