### ISSUE TITLE
Exp theme vis QA: button - Target:  Jan 15

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/carbon-for-ibm-dotcom#3138] opened 2020-07-14 15:02 UTC
Visual QA the following component:
http://carbon-expressive.mybluemix.net/?path=/story/buttons--default

The original specs are here: https://ibm.box.com/s/vf73go55h3mzq35baz3ex1haa5p4rrjd
Sketch file that reflects the visual: https://ibm.box.com/s/0di6rbglia22ua5jidb08kir1y1ffvix

**Comment by wonilsuhibm** [comment] 2020-07-14 15:07
I see some spacing discrepancies.

<img width="318" alt="Screen Shot 2020-07-14 at 11 06 47 AM" src="https://user-images.githubusercontent.com/30183447/87442305-1e3f1780-c5c2-11ea-87e3-f7d515f18f60.png">

**Comment by asudoh** [comment] 2020-07-15 00:13
Refs carbon-design-system/carbon#6457.

**Comment by RobertaJHahn** [comment] 2020-09-28 22:25
@asudoh Not sure what to do with this issue, so I am moving it to the next sprint, 20-20

**Comment by asudoh** [comment] 2020-09-28 22:40
Makes sense @RobertaJHahn thanks - The next step here is verifying that the expressive button works as speced. I believe recent Carbon upgrade fixes this issue.

**Comment by RobertaJHahn** [comment] 2020-09-29 17:48
Removing assignees and moving this issue into the `To do this sprint` pipeline so that any developer can pick it up.

**Comment by asudoh** [comment] 2020-09-29 23:50
Just FYI, I meant that the next step is a QA step by:

> The next step here is verifying that the expressive button works as speced.

**Comment by RobertaJHahn** [comment] 2020-10-12 22:03
@wonilsuhibm I hate to do this, but I have added you as Assignee to this issue.  Could you verify that this component is working as intended.  Thanks.

**Comment by RobertaJHahn** [comment] 2021-02-25 15:51
@shixiedesign I have added you to this issue as it is one of Wonil's issues he didn't get a chance to finish.  Can you take a look quickly and hopefully move it to `done`.

**Comment by RobertaJHahn** [comment] 2021-02-25 20:13
Olivia and Shixie will be reviewing the Carbon components and will open additional issues if there is a problem with the Carbon for ibm.com versions.  This is not an issue in Carbon expressive Storybook.

**Closed** 2021-02-26 17:32 UTC
Labels: Airtable Done, design, dev, package: react, priority: low
