### ISSUE TITLE
Pictogram is too small in pictogram item

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-for-ibm-dotcom#1453] opened 2020-02-24 17:36 UTC
## Detailed description

** Describe in detail the problem you're having**
The pictograms are displaying too small in the pictogram item, the specs show the pictogram at 80px

Recently James discovered that `carbon changed pictogram sizes from 32px to 48px`, it looks like the canvas size was increase but the artwork was not increased.

We might need to re-evaluate the size of the pictograms and adjust per the new canvas/artwork size
*OR*
Submit a feature request to Carbon to remove/change the excess canvas size to artwork.

**Is this a feature request (new component, new icon), a bug, or a general issue?**
design defect (might be a feature request to Carbon team)

**Is this issue related to a specific component?**
Pictogram item

**What did you expect to happen? What happened instead? What would you like to see changed?**

Intended design
![Screen Shot 2020-02-24 at 11.27.44 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/0cfbc3dd-a5e2-4329-8530-ce8e1ff60a32)

What's happening
![Screen Shot 2020-02-24 at 10.46.00 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/640b7ecb-a74e-432e-a05b-4bf4dd2a0d37)

**What browser are you working in**
Chrome

> What version of the IBM.com Library are you using?

**What offering/product do you work on? Any pressing ship or release dates we should be aware of?**
Web simplification

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

Intended Design
![Screen Shot 2020-02-24 at 11.33.49 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/b61ad1ae-8ac0-4b4f-bd0d-4d5b749d41cf)

Current
![Screen Shot 2020-02-24 at 11.33.28 AM.png](https://images.zenhubusercontent.com/5cacfd2d41f23a1e95e068dc/59bdb23a-4ee5-46f9-8951-e6ff85fc24ca)

**Comment by RobertaJHahn** [comment] 2020-02-25 14:12
@wonilsuhibm  There are implications if dev adjusts the size differently than Carbon.  Engineering agrees that the fix may require changes on the Carbon side.  A design decision is needed around whether less padding is needed.  Engineers feel this is not a bug, but a feature request.

**Comment by oliviaflory** [comment] 2020-03-05 21:09
[Link to the issue](https://github.com/carbon-design-system/carbon/issues/5550) on Carbon board to track the problems we hare having with pictograms.

**Comment by oliviaflory** [comment] 2020-03-24 19:19
**Update**

I spoke with Russ, Conrad and Josh on March 20, they explained that the SVGs are output with extra padding for non-power users that might be using the pictograms within Powerpoint. 

They agreed that there is still a need for pictograms to have no padding and are working on how they can implement that.

**Comment by oliviaflory** [comment] 2020-03-24 21:36
New issue number on the [Carbon board](https://github.com/carbon-design-system/carbon/issues/5693)

**Comment by RobertaJHahn** [comment] 2020-06-22 14:45
Dependency on Carbon.  Moving to icebox to wait until they have available resources to work on it.

**Comment by photodow** [comment] 2020-12-03 23:52
@oliviaflory @jeffchew did this one get resolved?

https://percy.io/538fc19a/Carbon-for-IBM.com-React/builds/7957132?utm_campaign=538fc19a&utm_content=Carbon-for-IBM.com-React&utm_source=github_status_public

![image](https://user-images.githubusercontent.com/3793636/101104194-383cbf00-3590-11eb-919f-8258521bd4db.png)

**Closed** 2020-12-08 19:12 UTC
Labels: Airtable Done, Feature request, adopter support, adopter: Drupal, dev, package: react, priority: medium
